### Circular masks

In here you can test how the size affects, for example.

In [3]:
import numpy as np
from numba import jit

In [9]:
@jit(nopython=True)
def create_circular_mask(radius):
    """
    Creates a fast and efficient circular mask compatible with Dask and large-scale operations.
    """
    size = 2 * radius + 1
    kernel = np.zeros((size, size), dtype=np.uint8)
    for y in range(size):
        for x in range(size):
            if (x - radius) ** 2 + (y - radius) ** 2 <= radius ** 2:
                kernel[y, x] = 1
    kernel[radius, radius] = 0  # Exclude the center
    return kernel

# Example usage:
radius = 5
circular_mask = create_circular_mask(radius)
print(circular_mask)

[[0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]]
